# Generated by Django 3.0.8 on 2020-07-16 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
